# ARSHIF Financial Hall — Certification Portal

A sovereign, local-first financial education portal built as a single-file vanilla HTML/CSS/JavaScript application. The portal is designed for learners, families, artists, entrepreneurs, homeschool programs, community builders, and self-directed adults who want a structured path through money literacy, consumer protection, budgeting, credit, debt, investing literacy, taxes, insurance, fraud prevention, ethics, and long-term stewardship.

> **Important boundary:** This project provides general financial education only. It is not individualized investment, tax, legal, insurance, benefits, accounting, or financial-adviser advice. The certificate generated by the portal is an ARSHIF Certificate of Completion, not an accredited degree, government license, securities license, tax-preparer credential, or professional financial-planning credential.

---

## Live Site

When published through GitHub Pages, this project can be served as a static website.

Suggested repository structure:

```text
financial-hall/
├── index.html
├── README.md
└── LICENSE.md
```

If this portal is part of a larger ARSHIF, Khaemenes Academy, Verve N Veda, or Ohmic Foundry repository, place the file inside its own folder and link to it from the main landing page.

---

## What This Portal Includes

The upgraded Financial Hall build includes:

- 48-module financial education course
- 152-dossier financial atlas
- 240 module-specific quiz questions
- 5 quiz questions per module
- Midterm and final assessment structure
- 80% mastery retake philosophy
- Certificate of completion generator
- Capstone: Personal Financial Stewardship Plan
- Budgeting, debt, compound interest, and break-even tools
- Monte Carlo Resilience Processor
- Student Vault export/import system
- Encrypted vault export/import with parent passphrase
- Recovery snapshots
- Storage-health status
- Record fingerprint/checksum
- Source vault with official and durable education pathways
- GitHub upload safety checklist
- Fully scoped ARSHIF visual design
- Vanilla HTML, CSS, and JavaScript
- No external libraries required

---

## Educational Scope

The course covers:

1. Money, values, and financial well-being
2. Financial goal architecture
3. Income, paychecks, and benefits
4. Banking foundations
5. Budgeting and cash-flow mapping
6. Needs, wants, and opportunity cost
7. Emergency funds and shock planning
8. Saving systems and sinking funds
9. Consumer math
10. Credit reports and credit scores
11. Credit cards
12. Loans, APR, and amortization
13. Debt payoff strategy
14. Auto finance and transportation costs
15. Renting and housing basics
16. Mortgage literacy
17. Taxes and recordkeeping basics
18. Student aid and education finance
19. Insurance and risk transfer
20. Health insurance and medical bills
21. Identity theft and account security
22. Fraud, scams, and consumer protection
23. Investing foundations
24. Compound interest and time
25. Risk, return, diversification, and asset allocation
26. Stocks, bonds, funds, and ETFs
27. Retirement accounts and long-term planning
28. Inflation, interest rates, and the economy
29. Behavioral finance and money emotions
30. Family financial communication
31. Youth money education
32. Self-employment and gig work finance
33. Small business financial basics
34. Bookkeeping and recordkeeping
35. Nonprofit, campaign, and community stewardship basics
36. Charitable giving and mutual aid
37. Estate planning literacy
38. Financial emergency and disaster preparedness
39. Consumer rights and complaints
40. Ethics, fiduciary duty, and professional boundaries
41. Public benefits and community resource navigation
42. Financial data literacy and privacy
43. Digital payments, crypto, and speculation cautions
44. Financial research and source verification
45. Career, credentials, and income growth
46. Financial independence concepts
47. Annual financial review ritual
48. Personal Financial Stewardship Plan capstone

---

## What This Portal Does Not Do

This portal does **not**:

- Recommend specific investments
- Provide individualized tax advice
- Provide individualized legal advice
- Provide individualized insurance advice
- Provide professional accounting services
- Replace a licensed financial adviser, CPA, attorney, insurance agent, benefits counselor, or government agency
- Guarantee financial outcomes
- Certify someone as a licensed financial professional

All learners should verify current rules, rates, deadlines, and eligibility requirements through official sources or qualified professionals.

---

## Privacy and Local Storage

This portal is designed to be **local-first**. Learner progress, notes, scores, capstone work, vault records, and saved data are stored in the browser using local storage unless exported by the user.

### Do Not Upload Private Records

When publishing this project to GitHub, upload only the public portal files.

Do **not** upload:

- Student Vault JSON exports
- Encrypted vault exports
- Learner names
- Notes
- Capstone drafts
- Financial records
- Budget data
- Income information
- Account information
- Private family records
- Screenshots containing personal information
- Certificate exports with private names unless intentionally shared

Recommended `.gitignore` additions:

```gitignore
# Private ARSHIF vault exports
*student-vault*.json
*financial-vault*.json
*encrypted-vault*.json
*student-record*.json
*progress-report*.json
*capstone*.json
/private/
/exports/
```

---

## Student Vault and Backup Guidance

The Student Vault supports:

- Exporting a learner record as JSON
- Importing that record on another computer
- Exporting an encrypted vault with a passphrase
- Importing the encrypted vault later
- Creating emergency snapshots
- Restoring recovery snapshots

For dual-computer access, use this rhythm:

1. Complete learning work on Computer A.
2. Export the Student Record JSON or encrypted vault.
3. Save it to a trusted private storage location.
4. Open the portal on Computer B.
5. Import the latest vault file.
6. Continue work.
7. Export again at the end of the session.

This is not cloud sync. It is a portable backup workflow.

---

## GitHub Pages Setup

To publish this portal using GitHub Pages:

1. Create a new GitHub repository.
2. Add the upgraded portal file.
3. Rename the portal file to `index.html` if this repository will host only this portal.
4. Add this `README.md` file.
5. Add a `LICENSE.md` file if needed.
6. Go to **Settings → Pages**.
7. Choose the branch, usually `main`.
8. Choose the root folder or `/docs` folder.
9. Save and wait for GitHub Pages to build.
10. Test the portal in a private browser window.

---

## Suggested File Names

Recommended public files:

```text
index.html
README.md
LICENSE.md
THIRD_PARTY_NOTICES.md
```

If hosted inside a larger website:

```text
/financial/index.html
/financial/README.md
```

---

## Source Philosophy

The portal is built around official, public, durable, and educational source pathways, including:

- Consumer Financial Protection Bureau educational tools
- FDIC Money Smart
- MyMoney.gov
- Investor.gov
- SEC EDGAR
- FINRA BrokerCheck
- IRS small business and tax resources
- AnnualCreditReport.com
- FTC ReportFraud
- IdentityTheft.gov
- StudentAid.gov
- Federal Reserve education resources
- FRED economic data
- Bureau of Labor Statistics career data
- O*NET career research
- SBA learning resources

The portal should prefer official sources when rules, rights, deadlines, tax issues, consumer protections, financial aid, or regulated financial products are involved.

---

## Certification Philosophy

The Financial Hall certificate is meant to recognize completion of the portal’s educational pathway. It should be framed as:

- A learning record
- A homeschool or independent-study artifact
- A portfolio item
- A personal development milestone
- A community education certificate

It should **not** be represented as:

- A securities license
- A financial adviser credential
- A government-approved certification
- A tax-preparer license
- A legal or accounting credential
- An accredited college degree

---

## Accessibility and Usability Goals

Future improvements may include:

- Larger-print mode
- Light-mode toggle
- Keyboard navigation audit
- Screen-reader landmark improvements
- Plain-language mode
- Youth mode
- Parent/teacher dashboard
- Printable worksheets for each module
- Offline PDF workbook export
- Multi-language glossary

---

## Suggested Future Upgrades

Potential next versions:

- **v4 Teacher/Parent Hub:** instructor notes, lesson pacing, daily trivia, discussion cards, and family money-meeting prompts.
- **v5 Global Rules Layer:** country/state-specific consumer-rights, tax-source, benefits-source, and financial-aid-source routing.
- **v6 Workbook Export:** printable worksheets for all 48 modules.
- **v7 Course Builder:** custom tracks for teens, artists, entrepreneurs, nonprofit leaders, campaign treasurers, seniors, and families.
- **v8 Accessibility Pass:** full keyboard testing, ARIA review, contrast improvements, and screen-reader optimization.

---

## Repository Safety Checklist

Before publishing:

- [ ] Rename the portal file to `index.html` if needed.
- [ ] Confirm no private JSON vault files are included.
- [ ] Confirm no learner names or financial records are committed.
- [ ] Confirm no personal capstone drafts are committed.
- [ ] Add `README.md`.
- [ ] Add `LICENSE.md`.
- [ ] Add `.gitignore` protections for vault exports.
- [ ] Test all tabs after GitHub Pages deploys.
- [ ] Test Student Vault export/import locally.
- [ ] Test certificate generation with sample data only.
- [ ] Keep the financial education disclaimer visible.

---

## License

Choose a license that matches your goals.

If this is part of a protected ARSHIF, Khaemenes Academy, Verve N Veda, or Ohmic Foundry project, use your project’s public-facing license terms. If the code is not intended for unrestricted reuse, do not apply a permissive open-source license by accident.

---

## Project Note

ARSHIF Financial Hall is built as a stewardship-centered learning environment. It is designed to help people slow down, verify sources, understand financial systems, protect themselves from harm, and build more stable households and communities.
